# Generated by Django 5.1 on 2024-11-24 20:27

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("milas_per_tupper", models.IntegerField()),
                ("reorder_threshold", models.IntegerField(default=10)),
                ("reorder_tuppers", models.IntegerField(default=10)),
                ("is_order_pending", models.BooleanField(default=False)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("days_until_expiration", models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name="Refrigerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True,
                        choices=[("ADMIN", "Admin"), ("EMPLOYEE", "Employee")],
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("FULFILLMENT", "Supplier Order Fulfillment"),
                            ("SALE", "Sale of Milanesas"),
                            ("ADMIN_ACTION", "Inventory Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_repr", models.CharField(max_length=200)),
                ("action_description", models.TextField()),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuppers_requested", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tuppers_remaining", models.IntegerField()),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.cut"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuppers_allocated", models.IntegerField()),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.column",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="column",
            name="refrigerator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.refrigerator"
            ),
        ),
        migrations.CreateModel(
            name="SubColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_tuppers", models.IntegerField(default=0)),
                ("milas_tupper_in_use", models.IntegerField(default=0)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.column",
                    ),
                ),
                (
                    "cut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.cut"
                    ),
                ),
            ],
        ),
    ]
