# Generated by Django 5.1 on 2024-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
