# Generated by Django 5.1 on 2024-09-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cut_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='is_order_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cut',
            name='reorder_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='cut',
            name='reorder_tuppers',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subcolumn',
            name='milas_tupper_in_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subcolumn',
            name='total_tuppers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuppers_requested', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cut')),
            ],
        ),
    ]
