# Generated by Django 5.1 on 2024-10-26 17:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cut_is_order_pending_cut_reorder_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='cut',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='cut',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tuppers_remaining',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
