# Generated by Django 5.1 on 2024-10-18 02:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_cut_is_order_pending_cut_reorder_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cut",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
