# Generated by Django 5.1 on 2024-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_order_fulfilled_order_tuppers_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="cut",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
