# Generated by Django 5.1 on 2024-10-25 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_cut_unit_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("EMPLOYEE", "Employee")],
                        max_length=10,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("FULFILLMENT", "Supplier Order Fulfillment"),
                            ("SALE", "Sale of Milanesas"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_repr", models.CharField(max_length=200)),
                ("action_description", models.TextField()),
                (
                    "action_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
