# Generated by Django 5.1 on 2024-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="action_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("FULFILLMENT", "Supplier Order Fulfillment"),
                    ("SALE", "Sale of Milanesas"),
                    ("ADMIN_ACTION", "Inventory Management"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[("ADMIN", "Admin"), ("EMPLOYEE", "Employee")],
                max_length=20,
            ),
        ),
    ]
