# Generated by Django 5.1 on 2024-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_order_scheduled_date_alter_actionlog_action_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cut",
            name="days_until_expiration",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="order",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
